# .github/workflows/ci.yml
name: CI - Lint, Format, Test

on:
  push:
    branches: [task/ep2-us5-global-layout-and-page-wrapper]
  pull_request:
    branches: [task/ep2-us5-global-layout-and-page-wrapper]

jobs:
  validate:
    name: Lint, Prettier, Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Check formatting with Prettier
        run: npm run prettier:check

      - name: Run Unit Tests
        run: npm test
